### ISSUE TITLE
Docs missing

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemoflex#17]
There is no docs. The readme should be more descriptive as well.

**Comment by jnnr** [comment]
Could you take care of this, @MaGering ?

**Comment by jnnr** [comment]
For starters, the docs should at least contain the api docs, a what's new and a page with these sections:

* Introduction
* Installation
* Getting started

**Comment by MaGering** [comment]
> For starters, the docs should at least contain the api docs, a what's new and a page with these sections:
> 
>     * Introduction
> 
>     * Installation
> 
>     * Getting started

Did you already have a name for that page in mind? I was thinking naming it `basic_usage.rst` but perhaps you have a more suitable suggestion?

And should I already add an api directory with a `oemoflex.rst` file analogous to how we did it in [oemof-thermal](https://github.com/oemof/oemof-thermal/tree/dev/docs/api)?

**Comment by jnnr** [comment]
@MaGering: You could do it parallel to oemof-b3:

Getting started

   overview
   getting_started
   examples

Reference

   whats_new
   api

**Comment by MaGering** [comment]
> @MaGering: You could do it parallel to oemof-b3:
> 
> Getting started
> 
> overview
> getting_started
> examples
> 
> Reference
> 
> whats_new
> api

Okay! So should I add `Introduction` and `Installation` as subsections to `overview`?
And should I add `literature` to `Reference` as in `oemof-b3`?

**Comment by jnnr** [comment]
> Okay! So should I add `Introduction` and `Installation` as subsections to `overview`?

There are many ways to do it. Best is to have a look at the oemof-b3 docs. Overview is some general text on what this is. Getting started explains how to install it.

> And should I add `literature` to `Reference` as in `oemof-b3`?

I guess we do not have literature yet in this repo.
