### ISSUE TITLE
Obsolete installation of oemof with oemof.tabular?

### ISSUE THREAD

**Issue by MaGering** [rl-institut/oemoflex#41]
`oemof` is installed with the installation of `oemof.tabular` in `install_requires`  of `oemoflex`' `setup.py`. As far as I'm concerned `oemof` is obsolete and might lead to errors when using it. Should we consider dropping `oemof` from  the `install_requires`?

_Originally posted by @MaGering in https://github.com/rl-institut/oemoflex/issues/26#issuecomment-930285498_

**Comment by jnnr** [comment]
@MaGering, can we close this issue?

**Comment by MaGering** [comment]
Isn't this only fixed with merge of https://github.com/oemof/oemof-tabular/pull/21?

**Comment by jnnr** [comment]
> Isn't this only fixed with merge of [oemof/oemof-tabular#21](https://github.com/oemof/oemof-tabular/pull/21)?

It is indeed an issue that oemof.tabular's release is delayed. However, this is an issue of oemof.tabular. There may arise issues for oemoflex because of that. But the problem of obsolete dependencies is mentioned here belongs to oemof.tabular.
