### ISSUE TITLE
Release v0.0.1

### ISSUE THREAD

**Issue by jnnr** [rl-institut/oemoflex#58]
### Preparation
* Finish issues and PRs related to the release
* [x] Increase version that is installed running `pip install oemoflex`
* [x] Test the examples
* [x] Keep an eye on open issues that are set to your release but seem to be forgotten.
* [x] Check that the docs look good. 
 
### Day of release
* Optional: Open a release branch to avoid conflicts with other uses while the release progress.
* [x] Close "forgotten" issues with a recapitulatory comment or set them to a later release if they are still important.
* Test if everything works
* If you have failing test fix them or postpone the release.
* Check the whatsnew-file 
* Check if the *latest* documentation looks right at readthedocs.
* Change the version number everywhere!!! (e.g. from 0.2.1dev to 0.2.1) -> `pyproject.yaml` and `docs/conf.py`
* If everything seems to work, merge the release branch into the main branch. (--no-ff)
* Push your local main branch to the remote.
* Set a [release on github](../releases). Select the **main** branch (default: dev)! A label is set automatically.
* Use `git fetch` to see the label in your local main branch.
* Merge the release branch into the dev branch. (--no-ff)
* Remove the obsolete release branch.
* Prepare the dev branch for further development: Adapt the version number at (e.g. from 0.2.1 to 0.2.2dev). Also add a new whatsnew file and a link in the [whatsnew.rst file](../tree/dev/doc/whats_new.rst). Open the file locally or use the *RAW* button to see the links.
* Close the release issue with informations for the community and relax

**Comment by MaGering** [comment]
Running the examples locally I've seen that they are failing because

1. `from oemof.outputlib.processing import parameter_as_dict` should be imported from solph and not from outputlib and
2.  because of `KeyError: 'investment_ep_costs'` running `simple_model.py`. `investment_ep_costs` is hardcoded in [these lines](https://github.com/rl-institut/oemoflex/blob/29badeb575ed2f0894a24b5402f5c7653555aed6/oemoflex/model/postprocessing.py#L641-L651) in postprocessing.py.

**Comment by henhuy** [comment]
> 2\. because of `KeyError: 'investment_ep_costs'` running `simple_model.py`. `investment_ep_costs` is hardcoded in [these lines](https://github.com/rl-institut/oemoflex/blob/29badeb575ed2f0894a24b5402f5c7653555aed6/oemoflex/model/postprocessing.py#L641-L651) in postprocessing.py.

I think this is due to missing values in results. I encountered the same, when trying to calculate results from your model in digiplan. We can talk about this on RC, okay?
